import json
from pathlib import Path

# id -> lang -> (question, a, b, c)
T = {}

def add(i, **langs):
    T[i] = langs

add(1, ru=("Три цвета светофора:", "красный, зелёный и жёлтый", "красный, зелёный и синий", "жёлтый, зелёный и синий"), es=("Los tres colores del semáforo son:", "rojo, verde y amarillo", "rojo, verde y azul", "amarillo, verde y azul"), pt=("As três cores do semáforo são:", "vermelho, verde e amarelo", "vermelho, verde e azul", "amarelo, verde e azul"), fr=("Les trois couleurs du feu sont :", "rouge, vert et jaune", "rouge, vert et bleu", "jaune, vert et bleu"), de=("Die drei Farben der Ampel sind:", "Rot, Grün und Gelb", "Rot, Grün und Blau", "Gelb, Grün und Blau"))
add(2, ru=("Жёлтые треугольные знаки сообщают какую информацию", "предупреждение", "больница напротив", "ограничение скорости"), es=("¿Qué información dan las señales triangulares amarillas?", "advertencia", "hospital enfrente", "límite de velocidad"), pt=("Que informação dão as placas triangulares amarelas?", "advertência", "hospital em frente", "limite de velocidade"), fr=("Quelle information donnent les panneaux triangulaires jaunes ?", "avertissement", "hôpital en face", "limitation de vitesse"), de=("Welche Information geben gelbe dreieckige Schilder?", "Warnung", "Krankenhaus gegenüber", "Geschwindigkeitsbegrenzung"))
add(3, ru=("Какие из этих дорожных знаков синие?", "предписывающие знаки", "информационные знаки", "знаки опасности"), es=("¿Cuáles de estas señales son azules?", "señales reglamentarias", "señales de información", "señales de peligro"), pt=("Quais destas placas são azuis?", "placas de regulamentação", "placas de informação", "placas de perigo"), fr=("Lesquels de ces panneaux sont bleus ?", "panneaux de réglementation", "panneaux d'information", "panneaux de danger"), de=("Welche dieser Verkehrszeichen sind blau?", "Vorschriftszeichen", "Hinweiszeichen", "Gefahrenzeichen"))
add(4, ru=("Постоянный зелёный сигнал означает", "нужно уступить всем пешеходам и водителям, которые уже на перекрёстке", "можно ехать, это безопасно", "осторожно проехать перекрёсток, пока свет не стал красным"), es=("Una luz verde fija significa", "debes ceder a peatones y conductores que ya usan el cruce", "avanza, es seguro hacerlo", "cruza con precaución antes de que cambie a rojo"), pt=("Luz verde contínua significa", "você deve ceder a pedestres e motoristas que já estão no cruzamento", "siga, é seguro", "atravesse com cautela antes de ficar vermelho"), fr=("Un feu vert fixe signifie", "vous devez céder aux piétons et conducteurs déjà dans le carrefour", "avancez, c'est sûr", "traversez prudemment avant le rouge"), de=("Dauergrün bedeutet", "Sie müssen Fußgängern und Fahrern im Kreuzungsbereich Vorfahrt gewähren", "fahren, es ist sicher", "vorsichtig durchfahren, bevor es rot wird"))
add(5, ru=("Мигающий жёлтый на переходе означает", "осторожно — снизьте скорость и проезжайте осторожно", "остановитесь и ждите, пока мигание не прекратится", "ждите зелёный"), es=("Una luz amarilla intermitente en un cruce significa", "precaución: reduzca y avance con cuidado", "pare y espere hasta que deje de parpadear", "espere la luz verde"), pt=("Luz amarela piscando num cruzamento significa", "atenção: reduza e siga com cuidado", "pare e espere até parar de piscar", "espere o verde"), fr=("Un feu jaune clignotant à un passage signifie", "prudence : ralentissez et avancez avec précaution", "arrêtez-vous jusqu'à la fin du clignotement", "attendez le vert"), de=("Gelb blinkend an einem Übergang bedeutet", "Vorsicht: langsamer fahren und vorsichtig weiterfahren", "anhalten, bis das Blinken aufhört", "auf Grün warten"))
add(6, ru=("Сплошная белая линия у правого края дороги уходит влево. Это значит, что", "впереди стык с перекрёстком", "дорога сузится", "вы приближаетесь к зоне работ"), es=("Una línea blanca continua en el borde derecho se inclina hacia tu izquierda. Esto indica que", "hay un empalme de cruce adelante", "la vía se estrechará", "te acercas a una zona de obras"), pt=("Uma linha branca contínua na borda direita se inclina para a esquerda. Isso mostra que", "há um entroncamento à frente", "a pista vai estreitar", "você se aproxima de uma obra"), fr=("Une ligne blanche continue au bord droit se rapproche vers la gauche. Cela montre que", "il y a un carrefour devant", "la route va se rétrécir", "vous approchez d'un chantier"), de=("Eine durchgezogene weiße Linie am rechten Rand läuft nach links. Das zeigt, dass", "vorne eine Kreuzung anschließt", "die Straße schmaler wird", "Sie sich einer Baustelle nähern"))
add(7, ru=("Вы в зоне, где обгон запрещён, если центр дороги обозначен", "прерывистой жёлтой линией", "прерывистой белой линией", "двумя сплошными жёлтыми линиями"), es=("Estás en zona de no adelantar cuando el centro de la vía está marcado por", "una línea amarilla discontinua", "una línea blanca discontinua", "dos líneas amarillas continuas"), pt=("Você está em zona de ultrapassagem proibida quando o centro da via é marcado por", "uma linha amarela tracejada", "uma linha branca tracejada", "duas linhas amarelas contínuas"), fr=("Vous êtes en zone d'interdiction de dépasser si le centre est marqué par", "une ligne jaune discontinue", "une ligne blanche discontinue", "deux lignes jaunes continues"), de=("Überholverbot gilt, wenn die Mitte markiert ist durch", "eine unterbrochene gelbe Linie", "eine unterbrochene weiße Linie", "zwei durchgezogene gelbe Linien"))
add(8, ru=("Если на покрытии нарисованы стрелки, водители должны:", "ехать в направлении стрелок", "замедлиться и быть готовыми уступить дорогу", "не перестраиваться"), es=("Cuando hay flechas pintadas en el pavimento, los conductores deben:", "ir en la dirección de las flechas", "reducir y prepararse para ceder el paso", "no cambiar de carril"), pt=("Quando há setas pintadas no pavimento, os motoristas devem:", "seguir a direção das setas", "reduzir e se preparar para ceder a passagem", "não mudar de faixa"), fr=("Quand des flèches sont peintes au sol, les conducteurs doivent :", "aller dans le sens des flèches", "ralentir et se préparer à céder le passage", "ne pas changer de voie"), de=("Wenn Pfeile auf die Fahrbahn gemalt sind, müssen Fahrer:", "in Richtung der Pfeile fahren", "langsamer werden und Vorfahrt gewähren können", "nicht die Spur wechseln"))
add(9, ru=("Сплошные жёлтые линии можно пересекать только чтобы:", "сменить полосу", "повернуть налево", "повернуть направо"), es=("No puedes cruzar líneas amarillas continuas excepto para:", "cambiar de carril", "girar a la izquierda", "girar a la derecha"), pt=("Você não pode cruzar linhas amarelas contínuas, exceto para:", "mudar de faixa", "virar à esquerda", "virar à direita"), fr=("Vous ne pouvez franchir des lignes jaunes continues que pour :", "changer de voie", "tourner à gauche", "tourner à droite"), de=("Durchgezogene gelbe Linien dürfen Sie nur überqueren, um:", "die Spur zu wechseln", "links abzubiegen", "rechts abzubiegen"))
add(10, ru=("Двойные сплошные жёлтые линии", "нельзя пересекать, кроме как с особой осторожностью", "нельзя пересекать никогда", "не разрешают смену полосы"), es=("Las líneas dobles amarillas continuas", "no deben cruzarse salvo con mucho cuidado", "no deben cruzarse nunca", "no permiten cambiar de carril"), pt=("Linhas duplas amarelas contínuas", "não devem ser cruzadas, salvo com muito cuidado", "não devem ser cruzadas nunca", "não permitem mudar de faixa"), fr=("Les doubles lignes jaunes continues", "ne doivent pas être franchies sauf grande prudence", "ne doivent jamais être franchies", "interdisent le changement de voie"), de=("Doppelte durchgezogene gelbe Linien", "dürfen nur mit besonderer Vorsicht überquert werden", "dürfen nie überquert werden", "erlauben keinen Spurwechsel"))

exec(Path(__file__).with_name("gen_rest.py").read_text(), {"add": add, "T": T})
exec(Path(__file__).with_name("gen_rest2.py").read_text(), {"add": add, "T": T})
exec(Path(__file__).with_name("gen_rest3.py").read_text(), {"add": add, "T": T})

root = Path(__file__).resolve().parents[1] / "src" / "content" / "translations"
root.mkdir(parents=True, exist_ok=True)
langs = ["ru", "es", "pt", "fr", "de"]
files = {"ru": "ru.json", "es": "es.json", "pt": "pt-BR.json", "fr": "fr.json", "de": "de.json"}
for lang in langs:
    payload = {}
    for qid, pack in T.items():
        q, a, b, c = pack[lang]
        payload[str(qid)] = {"q": q, "a": a, "b": b, "c": c}
    (root / files[lang]).write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
print("questions", len(T))
